name: build_agent

on:
  push:
    paths:
      - "AgentServer/**"
      - ".github/workflows/build_agent.yml"
  pull_request:
    paths:
      - "AgentServer/**"
      - ".github/workflows/build_agent.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MaaFramework
          fileName: "MAA-win-x86_64*"
          latest: true
          out-file-path: "deps"
          extract: true
      
      - name: Download MaaDeps
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MaaDeps
          fileName: "MaaDeps-x64-windows-devel.tar.xz"
          latest: true
          out-file-path: "deps"
          extract: false
          
      - name: Extract MaaDeps
        run: |
          mkdir -p deps/MaaDeps
          tar -xf deps/MaaDeps-x64-windows-devel.tar.xz -C deps/MaaDeps

      - name: Configure CMake
        shell: pwsh
        run: |
          cmake -S AgentServer -B AgentServer/build

      - name: Build
        shell: pwsh
        run: |
          cmake --build AgentServer/build --config Release -j

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MaaPCRAgentServer
          path: agent
